### ISSUE TITLE
Modify serializer response to hide videoroom owner's ID

### ISSUE THREAD

**Issue by pzandre** [Adrianzctpa/provisoryname#3]
Line 8 of [this file](https://github.com/Adrianzctpa/provisoryname/blob/main/djangoreactfw/provisoryapi/serializers.py) will return owner: ID
It's a good practice to override the default serializer to return owner UUID. This can be achieved with the source attribute (something like `owner = serializers.CharField(source="uuid"`)

**Comment by pzandre** [comment]
This is just in case you assign a User instance to owner.

**Comment by Adrianzctpa** [comment]
Will leave this open as it will probably be the case on future
